### ISSUE TITLE
Make parsely_raw_data an installable terminal function

### ISSUE THREAD

**Issue by aldraco** [Parsely/parsely_raw_data#21]
Give the ability to call raw_data commands from anywhere, i.e.
`parsely_raw_data redshift create_table <args>`

instead of requiring being in the same directory.

**Comment by dan-blanchard** [comment]
We already have some console scripts setup that will work as long as you have the virtualenv activated.

https://github.com/Parsely/parsely_raw_data/blob/e06f18722b9cfe5eccea67a7cc45f8de2e08a9ff/setup.py#L88-L92

**Comment by aldraco** [comment]
Oh nice, thanks @dan-blanchard. I'll put those in the docs.
